version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mongoose
    versions:
    - 5.11.14
    - 5.11.15
    - 5.11.16
    - 5.11.17
    - 5.11.18
    - 5.11.19
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
    - 5.12.5
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
    - 10.1.1
    - 10.1.2
    - 10.1.3
  - dependency-name: socket.io
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 4.0.0
  - dependency-name: socket.io-client
    versions:
    - 3.1.1
    - 3.1.2
    - 4.0.0
  - dependency-name: mocha
    versions:
    - 8.3.0
    - 8.3.1
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.1
    - 4.3.3
  - dependency-name: react-bootstrap
    versions:
    - 1.4.3
    - 1.5.0
    - 1.5.1
  - dependency-name: query-string
    versions:
    - 6.13.8
    - 6.14.0
    - 6.14.1
  - dependency-name: react-player
    versions:
    - 2.8.2
  - dependency-name: supertest
    versions:
    - 6.1.3
  - dependency-name: bootstrap
    versions:
    - 4.6.0
  - dependency-name: nodemon
    versions:
    - 2.0.7
  - dependency-name: semantic-ui-react
    versions:
    - 2.0.3
  - dependency-name: axios
    versions:
    - 0.21.1
